services:
  api:
    container_name: weda-template-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__Provider=Sqlite
      - Database__ConnectionString=Data Source=/app/data/Weda.Template.sqlite
      - Nats__Broker__Url=nats://broker:4222
      - Nats__Bus__Url=nats://bus:4222
    volumes:
      - weda-data:/app/data
#if (wiki)
      - ./docs/wiki:/app/wwwroot/wiki
#endif
    depends_on:
      broker:
        condition: service_healthy
      bus:
        condition: service_healthy
    restart: on-failure

  broker:
    image: nats:latest
    container_name: weda-template-broker
    command: -js -n broker
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  bus:
    image: nats:latest
    container_name: weda-template-bus
    command: -js -n bus
    ports:
      - "4223:4222"
      - "8223:8222"
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  weda-data: