services:
  api:
    container_name: weda-template-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__Provider=InMemory
#if (wiki)
    volumes:
      - ./docs/wiki:/app/wwwroot/wiki
#endif
    restart: on-failure