services:
  api:
    container_name: weda-template-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__Provider=PostgreSql
      - Database__ConnectionString=Host=postgres;Port=5432;Database=weda_template;Username=postgres;Password=postgres
      - Nats__Broker__Url=nats://broker:4222
      - Nats__Bus__Url=nats://bus:4222
#if (wiki)
    volumes:
      - ./docs/wiki:/app/wwwroot/wiki
#endif
    depends_on:
      postgres:
        condition: service_healthy
      broker:
        condition: service_healthy
      bus:
        condition: service_healthy
    restart: on-failure

  postgres:
    image: postgres:16-alpine
    container_name: weda-template-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weda_template
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  broker:
    image: nats:latest
    container_name: weda-template-broker
    command: -js -n broker
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  bus:
    image: nats:latest
    container_name: weda-template-bus
    command: -js -n bus
    ports:
      - "4223:4222"
      - "8223:8222"
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres-data: